config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  authenticate :user, -> (user) { user.admin? } do
    # No route 'GET /sidekiq'
    # TODO root_path unless user.admin?
    mount Sidekiq::Web => '/sidekiq'
  end
  use_doorkeeper
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', 
  	                             password: 'secret', confirmation: 'verification', 
  	                             unlock: 'unblock', registration: 'register', 
  	                             sign_up: 'cmon_let_me_in' },
                                 controllers: { omniauth_callbacks: 'omniauth_callbacks/omniauth_callbacks'}
  root 'questions#index'
 
  resources :email_confirms, only: [:edit, :update]
  resources :authorizations, only: [:show]
  resources :users, only:[:update, :show]
  resources :searchings, only: [:create], defaults: { format: 'json' }

  concern :subscribtable do
    resources :subscribtions, defaults: { format: 'json' }, only: [:create, :show, :destroy]
  end

  concern :votable do
    resources :votes, defaults: { format: 'json' }, only: [:create, :destroy]
  end

  concern :commentable do
    resources :comments, only: [:create, :destroy]
  end

  resources :questions, concerns: [:votable, :commentable, :subscribtable], except: [:edit], shallow: true do
    resources :answers, concerns: [:votable, :commentable], only: [:create, :update, :destroy]
  end

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
        get :index, on: :collection 
      end
      resources :questions, only: [:index, :show, :new, :create], shallow: true do
        resources :answers, only: [:index, :show, :new, :create]
      end
    end
  end
  
  mount ActionCable.server => '/cable'

end

app/models/question.rb
class Question < ApplicationRecord
  include ActiveModel::Dirty
  include Voting
  include Attaching
  include Commenting
  include Subscribing
  include BelongingsOfUser

  has_many :answers, dependent: :destroy
  validates :title, :content, presence: true
  
  after_create :post_via_comet, :subscribe_on_new_answers
  after_update :question_newsletter

  scope :last_24_hours, -> { where(created_at: DateTime.yesterday) }

  def question_newsletter
    QuestionChangingsJob.perform_now(self) if self.content_changed?
  end
  
  private
  
    def subscribe_on_new_answers
      Subscribtion.create(user: user, subscribtable: self)
    end
  
    def post_via_comet
      ActionCable.server.broadcast '/questions',
                                    ApplicationController.render( 
                                    	                            partial: 'questions/new_question',
                                                                  locals: { question: self } 
                                                                 )
    end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  load_and_authorize_resource except: [:create]

  def index
    respond_with @questions
  end

  def new
    respond_with @question
  end

  def create
    authorize! :create, Question
    respond_with @question = current_resource_owner.questions.create!(question_params)
  end

  def show
    respond_with @question
  end

  private

  def question_params
    params.require(:question).permit(:title, :content)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :destroy]
  skip_authorization_check only: [:index]
  load_resource only: [:show, :update, :destroy, :new]
  authorize_resource
  before_action :authorship_verification, only: [:update, :destroy]

  respond_to :json, only: [:create, :destroy]

  def index
    respond_with(@questions = Question.all)
  end

  def new
    respond_with @question
  end

  def create
    @question = current_user.questions.create(question_params)
    respond_with @question do |format|
      if @question.errors.any?
        format.js { render json: @question.errors.full_messages, status: 422 }
        format.json { render json: @question.errors.full_messages, status: 422 }
      else
        format.js { render nothing: true }
        format.json { render json: @question }
      end
    end
  end

  def show
    @answers = @question.answers.best_first
    respond_with @question
  end

  def update
    @question.update(question_params)
    respond_with @question do |format|
      format.js { render nothing: true }
      format.json { render json: @question }
    end
    # respond_with @question
  end

  def destroy
    respond_with @question.destroy do |format|
      format.js { render nothing: true }
      format.json { render nothing: true }
    end
  end

  private

  def authorship_verification
    redirect_to @question, notice: 'Deny!' unless current_user.is_author_of?(@question)
  end

  def question_params
    params.require(:question).permit(:title, :content, attachments_attributes: [:id, :file, :_destroy]) 
  end

end

app/views/questions/_edit.html.haml
%div.button
 %p Edit Question
= form_for question, url: question_path(question), remote: true, html: {class: "edit_question_form edit-form"} do |f|
 = f.label :content, "Update Form"
 %br
 = f.text_field :content
 %br
 #attache-file-to-question
  - f.fields_for :attachments do |a|
   = render 'layouts/attachment_fields', f: a 
  = link_to_add_association 'add file', f, :attachments, partial: 'layouts/attachment_fields', class: "add-fields-link"
 %br
 = f.submit 'Update a question'
 %br
 = link_to 'Delete my Question', question, method: :delete, class: "delete_question_link"
%br

app/views/questions/_new_question.html.haml
= link_to question.title, question_path(question), html: { class: 'question-link' }

app/views/questions/create.js.erb
$('.notice-message').remove();
errors = '<%= j @question.errors.full_messages.join("\n") %>';

if (errors !== ''){
  alert(errors);
}

app/views/questions/edit.html.haml
%div.button
 %p Edit Question
= form_for @question, url: question_path(@question), remote: true, html: {class:"edit_question_form"} do |f|
 = f.label :content, "Update Form"
 %br
 = f.text_field :content
 %br
 / #attache-file-to-question
 /  = f.fields_for :attachable do |a|
 /   = render 'layouts/attachment_fields', f: a 
 /   = link_to_add_association 'add file', f, :attachments, partial: 'layouts/attachment_fields', class: "add-fields-link"
 /  = link_to_remove_association "remove file", f
 / %br
 = f.submit 'Update a question'
 %br
 = link_to 'Delete my Question', @question, method: :delete
%br

app/views/questions/index.html.erb
= link_to "Ask a question", new_question_path
%br
%h3 Question index
- @questions.each do |question|
    = link_to question.title, question_path(question)
    %br

app/views/questions/index.html.haml
/ =# link_to "Ask a question", new_question_path if can? :create, Question
%br
= render partial: 'layouts/searchings'
%br
.question-list
 - @questions.each do |question|
  .question
   = link_to question.title, question_path(question), html: { class: "question-link", id: "#{question.id}" }
  %br

app/views/questions/new.html.erb
= form_for @question, url: question_index_path, method: :post do |q|
  = q.label :title, 'Problem'
  = q.text_field :title
  = q.label :content, 'Description'
  = q.text_field :content
  = q.submit 'Ask for Help'
%br
%h3 Question new

app/views/questions/new.html.haml
.question-new
 = form_for @question, remote: true, :html => { :multipart => true } do |f|
  = f.label :title, 'Problem'
  %br
  = f.text_field :title
  %br
  = f.label :content, 'Description'
  %br
  = f.text_field :content
  %br
  #attache-file-to-question
   = f.fields_for :attachments do |a|
    = render 'layouts/attachment_fields', f: a 
   = link_to_add_association 'add file', f, :attachments, partial: 'layouts/attachment_fields', class: "add-fields-link "
  = f.submit 'Ask for Help'
  %br
 %br

app/views/questions/show.html.erb
%h3 Question Title
= @question.title
%br
%h3 Question Content
= @question.content
%br
- if user_signed_in? && current_user.is_author_of?(@question)
 = link_to 'Delete my Question', question_path(@question), method: :delete
 %br
%br
%h3 Question Answers
- @question.answers.each do |answer| 
 = answer.content
 - if user_signed_in? && current_user.is_author_of?(answer)
  = link_to 'Delete my Answer', question_answer_path(@question, answer.id), method: :delete
 %hr
= link_to 'Offer solution', new_question_answer_path(@question)
/ = link_to_function('Offer solution', "$(this).click($('.new_answer').fadeToggle())")

.new_answer
 %hr
 = render template: 'answer/new'
 %hr

%h3 Question Show

app/views/questions/show.html.haml
.questions 
 .subscriptions-block
  = render partial: "layouts/subscribable", locals: { parent_object: @question }
 .question{:class => dom_id(@question), :id => @question.id}
  %h3= @question.title
  .question_content
   %h3= @question.content
  = render partial: 'layouts/rating', locals: { parent_object: @question }
  - if user_signed_in? && current_user.is_author_of?(@question)
   = render partial: 'layouts/attached_files', locals: { parent_object: @question }
   - if can? :update, @question
    = render partial: 'questions/edit', locals: { question: @question }
  %br
  .comments
   .comment
   = render partial: @question.comments
  .new_commen
   - if can? :create, Comment
    = render partial: 'comments/new', locals: { parent_object: @question }
  %hr
.hidden_class
 .question
  = content_tag 'div', '', id: 'question-info', data: {question_id: @question.id, key2: 'val2'} 
  .comments
   = content_tag 'div', '', id: 'question-comments-info', data: {question_id: @question.id, content: 'val2'} 
- if can? :create, Answer
 = render partial: 'answers/new', locals: { question: @question }
%h2 Answers
.best_answer
.answers
 = render @answers
%hr