config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  authenticate :user, -> (user) { user.admin? } do
    # No route 'GET /sidekiq'
    # TODO root_path unless user.admin?
    mount Sidekiq::Web => '/sidekiq'
  end
  use_doorkeeper
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', 
  	                             password: 'secret', confirmation: 'verification', 
  	                             unlock: 'unblock', registration: 'register', 
  	                             sign_up: 'cmon_let_me_in' },
                                 controllers: { omniauth_callbacks: 'omniauth_callbacks/omniauth_callbacks'}
  root 'questions#index'
 
  resources :email_confirms, only: [:edit, :update]
  resources :authorizations, only: [:show]
  resources :users, only:[:update, :show]
  resources :searchings, only: [:create], defaults: { format: 'json' }

  concern :subscribtable do
    resources :subscribtions, defaults: { format: 'json' }, only: [:create, :show, :destroy]
  end

  concern :votable do
    resources :votes, defaults: { format: 'json' }, only: [:create, :destroy]
  end

  concern :commentable do
    resources :comments, only: [:create, :destroy]
  end

  resources :questions, concerns: [:votable, :commentable, :subscribtable], except: [:edit], shallow: true do
    resources :answers, concerns: [:votable, :commentable], only: [:create, :update, :destroy]
  end

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
        get :index, on: :collection 
      end
      resources :questions, only: [:index, :show, :new, :create], shallow: true do
        resources :answers, only: [:index, :show, :new, :create]
      end
    end
  end
  
  mount ActionCable.server => '/cable'

end

app/models/comment.rb
class Comment < ApplicationRecord
  include BelongingsOfUser

  belongs_to :parent, polymorphic: true
  validates :parent_type, :content, presence: true
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include Parent
  helper_method :parent_question_id, :parent, :channel_path
  before_action :parent, only: [:create]
  authorize_resource
  before_action :authorship_verification, only: [:destroy]
  
  respond_to :js, :json
  
  def create
    @comment = parent.comments.create(comment_params.merge(user: current_user))
    ActionCable.server.broadcast channel_path(@comment), @comment
    respond_with @comment
    # respond_with @comment do |format|
    #   format.js { render nothing: true }
    # end
  end

  def destroy
    respond_with @comment.delete do |format|
      format.js { render nothing: true }
    end
  end

  private

  def channel_path(comment)
    @to_question = "/question/#{parent_question_id}" 
    comment.parent_type == "Question" ? @path = @to_question : @path = @to_question + '/answers'
    @path += "/comments"
  end

  def authorship_verification
    @comment = Comment.find(params[:id])
    redirect_to @comment, notice: 'Deny!' unless current_user.is_author_of?(@comment)
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/views/comments/_comment.html.haml
.comment{:id => dom_id(comment)}
 - if comment.persisted?
  %p="User #{comment.user_id} says:"
  %strong= comment.content
  - if user_signed_in? && current_user.is_author_of?(comment)
   %br
   = link_to 'Delete my comment', comment_path(comment), remote: true, class: "comment-delete-link", method: :delete

app/views/comments/_new.html.haml
.new_comment
 - if parent_object.persisted? && user_signed_in?
  = form_for [parent_object, parent_object.comments.new], remote: true do |i|
   = i.label :content, "Your Comment"
   = i.text_field :content
   %br
   = i.submit "Post Comment"

app/views/comments/create.js.erb
// $('#<%= dom_id(parent) %>').children(".comments").children('.comment').last().append("<%=j render @comment %>");
// $('#comment_content').val('');

app/views/comments/new.html.haml
.new_comment
 - if parent_object.persisted? && user_signed_in?
  = form_for [parent_object, parent_object.comments.new], remote: true do |i|
   = i.label :content, "Your Comment"
   = i.text_field :content
   %br
   = i.submit "Post Comment"