config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  authenticate :user, -> (user) { user.admin? } do
    # No route 'GET /sidekiq'
    # TODO root_path unless user.admin?
    mount Sidekiq::Web => '/sidekiq'
  end
  use_doorkeeper
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', 
  	                             password: 'secret', confirmation: 'verification', 
  	                             unlock: 'unblock', registration: 'register', 
  	                             sign_up: 'cmon_let_me_in' },
                                 controllers: { omniauth_callbacks: 'omniauth_callbacks/omniauth_callbacks'}
  root 'questions#index'
 
  resources :email_confirms, only: [:edit, :update]
  resources :authorizations, only: [:show]
  resources :users, only:[:update, :show]
  resources :searchings, only: [:create], defaults: { format: 'json' }

  concern :subscribtable do
    resources :subscribtions, defaults: { format: 'json' }, only: [:create, :show, :destroy]
  end

  concern :votable do
    resources :votes, defaults: { format: 'json' }, only: [:create, :destroy]
  end

  concern :commentable do
    resources :comments, only: [:create, :destroy]
  end

  resources :questions, concerns: [:votable, :commentable, :subscribtable], except: [:edit], shallow: true do
    resources :answers, concerns: [:votable, :commentable], only: [:create, :update, :destroy]
  end

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
        get :index, on: :collection 
      end
      resources :questions, only: [:index, :show, :new, :create], shallow: true do
        resources :answers, only: [:index, :show, :new, :create]
      end
    end
  end
  
  mount ActionCable.server => '/cable'

end

app/models/answer.rb
class Answer < ApplicationRecord
  include Voting
  include Attaching
  include Commenting
  include BelongingsOfUser
  
  belongs_to :question

  validates :content, :question_id, presence: true
  after_create :new_answer_lettering
  before_update :check_of_best

  scope :best_first, -> { order(best_answer: :desc) }
  scope :not_best_answers, -> { where(best_answer: false) }
  
  private
  
  def new_answer_lettering
    NewAnswerLetteringJob.perform_now(self)
  end

  def check_of_best
    return unless @best_answer = question.answers.best_first.first
    return @best_answer.toggle(:best_answer).save unless ( id == @best_answer.id ) || ( !best_answer )
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  authorize_resource except: [:create]
  before_action :authorship_verification, only: [:update, :destroy]
  respond_to :js, :json

  def create
    authorize! :create, Answer
    @answer = Question.find(params[:question_id]).answers.create(answer_params.merge(user: current_user))
    ActionCable.server.broadcast "/question/#{@answer.question_id}/answers", @answer
    respond_with @answer
    # respond_with :api, :v1, @thing
  end

  def update
    @answer.update(answer_params)
    respond_with(@answer)
  end

  def destroy
    respond_with @answer.destroy do |format|
      format.js { render nothing: true }
      format.json { render head: :no_content }
    end
  end

  private

  def authorship_verification
    @answer ||= Answer.find(params[:id])
    redirect_to @answer.question, notice: 'Deny!' unless current_user.is_author_of?(@answer)
  end

  def answer_params
    params.require(:answer).permit(:content, :best_answer, attachments_attributes: [file:[]])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  load_and_authorize_resource except: [:create]

  def index
    respond_with @answers
  end

  def new
    respond_with @answer
  end

  def create
    authorize! :create, Answer
    respond_with @answer = current_resource_owner.answers.create!(answer_params.merge(question_id: params[:question_id].to_i))
  end

  def show
    respond_with @answer
  end

  private

  def answer_params
    params.require(:answer).permit(:content)
  end
end

app/views/answers/_answer.html.haml
.answer{:id => dom_id(answer)}
 .answer-content
  %strong= answer.content
 - if can? :update, answer.question
  = render partial: 'answers/best_voting', locals: { answer: answer }
 - if cannot? :update, answer.question
  = render partial: 'layouts/rating', locals: { parent_object: answer }
 = render partial: 'layouts/attached_files', locals: { parent_object: answer }
 - if answer.persisted? && user_signed_in? && current_user.is_author_of?(answer)
  - if can? :update, answer
   = render partial: 'answers/edit', locals: { answer: answer}
 .comments
  .comment
  = render partial: answer.comments

 .new_comment
  - if can? :create, Comment  
   = render partial: 'comments/new', locals: { parent_object: answer }

.hidden_class
 .answer
  = content_tag data: {answer: @answer}
  .comments
   = content_tag data: { comments: answer.comments }

app/views/answers/_best_voting.html.haml
- if answer.persisted? && user_signed_in? && current_user.is_author_of?(answer.question)
 = form_for answer, remote: true do |f|
  = f.label :best_answer, 'Is this Answer The Best?'
  = f.check_box :best_answer, { class: 'vote-check-box' }

app/views/answers/_comet_answer.html.haml
.answer{:id => dom_id(answer)}
 .answer-content
  %strong= answer.content
 = render partial: 'answers/best_voting', locals: { answer: answer }
 = render partial: 'layouts/rating', locals: { parent_object: answer }
 = render partial: 'layouts/attached_files', locals: { parent_object: answer }
 .comments
  .comment
  = render partial: answer.comments
  = render partial: 'answers/edit', locals: { answer: answer }
 .new_comment
  = render partial: 'comments/new', locals: { parent_object: answer }

app/views/answers/_edit.html.haml
%div.button-answer
 %p Edit Answer
= form_for answer, remote: true, html: { class: "edit_answer_form edit-form" } do |f|
 = f.label :content, "Update Form"
 %br
 = f.text_field :content
 %br
 #attache-file-to-answer
  = f.fields_for :attachments do |attache|
   = render 'layouts/attachment_fields', f: attache
  = link_to_add_association 'add file', f, :attachments, partial: 'layouts/attachment_fields', class: "add-fields-link"
 = link_to_remove_association "remove file", f
 %br
 = f.submit 'Update an answer'
 %br
 = link_to 'Delete my Answer', answer_path(answer), method: :delete, remote: true, class: 'delete_answer_link', 'data-turbolinks' => "false"
%br

app/views/answers/_just_answer.html.haml
.answer{:id => dom_id(answer)}
 .answer-content
  %strong= answer.content

app/views/answers/_new.html.haml
= form_for [question, question.answers.new], remote: true, html: {class: "new_answer"} do |f|
 = f.label :content, 'Form for Answer'
 %br
 = f.text_field :content
 #attache-file-to-answer
  = f.fields_for :attachments do |attache|
   = render 'layouts/attachment_fields', f: attache
 = link_to_add_association 'add file', f, :attachments, partial: 'layouts/attachment_fields', class: "add-fields-link"
 / = link_to_remove_association "remove file", f
 %br
 = f.submit 'Provide an answer'
 %hr

app/views/answers/_vote.html.haml
- if answer.persisted? && user_signed_in? && current_user.is_author_of?(answer.question)
 = form_for answer, remote: true do |f|
  = f.label :best_answer, 'Is this Answer The Best?'
  = f.check_box :best_answer, { class: 'vote-check-box' }

app/views/answers/create.js.erb
errors = '<%= j @answer.errors.full_messages.join('\n') %>';
if (errors !== ''){
  alert(errors)
}

app/views/answers/index.html.erb
%h2 index answer

app/views/answers/new.html.erb
= form_for @question.answers.new, url: question_answer_index_path(@question), method: :post do |a|
 = a.label :content, 'Form for Answer'
 = a.text_field :content
 = a.submit 'Provide an answer'
%h3 new answer

app/views/answers/show.html.erb
%h2 answer show

app/views/answers/update.js.erb
<% if @answer.errors.any? %>
  alert('<%= j @answer.errors.full_messages.join('\n') %>')
<% else %>
   $('#<%=dom_id(@answer, :edit)%>').parent('.answer').children('.answer-content').html('<strong><%= j @answer.content %></strong>');
   <%if @answer.best_answer %>
      $('.best_answer').children('.answer').prependTo('.answers');
      $('#<%=dom_id(@answer)%>').prependTo('.best_answer');
      $('.vote-check-box').prop("checked", false);
      $('#<%=dom_id(@answer)%>').find('.vote-check-box').prop("checked", true);
   <%end%>
   $('.edit_answer_form').hide();
<%end%>

app/views/answers/will_be_deleted_comet_answer.html.haml
.answer{:id => dom_id(answer)}
 .answer-content
  %strong= answer.content
 = render partial: 'answers/best_voting', locals: { answer: answer }
 = render partial: 'layouts/rating', locals: { parent_object: answer }
 = render partial: 'layouts/attached_files', locals: { parent_object: answer }
 .comments
  .comment
  = render partial: answer.comments
  = render partial: 'answers/edit', locals: { answer: answer }
 .new_comment
  = render partial: 'comments/new', locals: { parent_object: answer }