config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  authenticate :user, -> (user) { user.admin? } do
    # No route 'GET /sidekiq'
    # TODO root_path unless user.admin?
    mount Sidekiq::Web => '/sidekiq'
  end
  use_doorkeeper
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', 
  	                             password: 'secret', confirmation: 'verification', 
  	                             unlock: 'unblock', registration: 'register', 
  	                             sign_up: 'cmon_let_me_in' },
                                 controllers: { omniauth_callbacks: 'omniauth_callbacks/omniauth_callbacks'}
  root 'questions#index'
 
  resources :email_confirms, only: [:edit, :update]
  resources :authorizations, only: [:show]
  resources :users, only:[:update, :show]
  resources :searchings, only: [:create], defaults: { format: 'json' }

  concern :subscribtable do
    resources :subscribtions, defaults: { format: 'json' }, only: [:create, :show, :destroy]
  end

  concern :votable do
    resources :votes, defaults: { format: 'json' }, only: [:create, :destroy]
  end

  concern :commentable do
    resources :comments, only: [:create, :destroy]
  end

  resources :questions, concerns: [:votable, :commentable, :subscribtable], except: [:edit], shallow: true do
    resources :answers, concerns: [:votable, :commentable], only: [:create, :update, :destroy]
  end

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
        get :index, on: :collection 
      end
      resources :questions, only: [:index, :show, :new, :create], shallow: true do
        resources :answers, only: [:index, :show, :new, :create]
      end
    end
  end
  
  mount ActionCable.server => '/cable'

end

app/views/layouts/_attached_files.html.haml
.attached-files
 %h4 Attached files
 %ul
 - parent_object.attachments.each do |attached|
  %li
   = link_to attached.file.identifier, attached.file.url
   = link_to 'delete', root_path
   %br

app/views/layouts/_attachment_fields.html.haml
.attache-partial.nested-fields
 .field
  = f.label :file
  = f.file_field :file
 = link_to_remove_association "remove file", f

app/views/layouts/_exception.js.erb
alert("<%= exception.message %>");

app/views/layouts/_rating.html.haml
.rate-form
 %p="Total rate is #{parent_object.mark}"
 - if parent_object.persisted? && user_signed_in? && !current_user.is_author_of?(parent_object)
  = form_for [parent_object, parent_object.votes.new], remote: true do |i|
   = i.label :mark, "Good"
   = i.radio_button :mark, 1, id: "#{parent_object.class}s-rate", class: 'mark'
   %hr
   = i.label :mark, "Neutral"
   = i.radio_button :mark, 0, class: 'mark'
   %hr
   = i.label :mark, "Bad"
   = i.radio_button :mark, -1, class: 'mark'
   %hr
   - i.submit "Rate #{parent_object.class}"

app/views/layouts/_searchings.html.haml
.searching_form
 = form_tag "/searchings", method: "post", remote: true, id: "search_form" do
  = select_tag "area", options_for_select(["Global", "User", "Question", "Answer", "Comment"])
  = search_field_tag "query", "please type text here"
  = submit_tag "Search"
.search_result

app/views/layouts/_subscribable.html.haml
.subscribe-form
 - if parent_object.persisted? && user_signed_in? && !current_user.is_author_of?(parent_object)
  - if can? :create, Subscribtion
   - unless current_user.is_author_of?(@question)
    - if current_user.subscribtions.where(subscribtable: parent_object).first
     = button_to "Unsubscribe", subscribtion_path(current_user.subscribtions.where(subscribtable: parent_object).first), remote: true, method: :delete, id: "unsubscribe"
    - else
     = form_for [parent_object, parent_object.subscribtions.new], remote: true do |i|
      = i.submit "Subscribe", id: "subscribe"

app/views/layouts/_voting.html.haml
.rate-form
 %p="Total rate is #{parent_object.mark}"
 - if parent_object.persisted? && user_signed_in? && !current_user.is_author_of?(parent_object)
  = form_for [parent_object, parent_object.votes.new], remote: true do |i|
   = i.label :mark, "Good"
   = i.radio_button :mark, 1, id: "#{parent_object.class}s-rate"
   %hr
   = i.label :mark, "Bad"
   = i.radio_button :mark, -1
   %hr
   = i.submit "Rate #{parent_object.class}"
  - if @vote = parent_object.votes.where(user: current_user).first
   = link_to "Take back your voice", vote_path(@vote), method: :delete, remote: true

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QaThinknetikaApp</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<%#console%>
  <body>
  <div id="msg"></div>
  <%= link_to "Questions index", root_path %>
  <%= link_to "Questions new", new_question_path %>
  <%= link_to "My profile", user_path(current_user) if user_signed_in? %>
  <%= link_to "Log in", new_user_session_path unless user_signed_in? %>
  <%= link_to "Log out", destroy_user_session_path, method: :delete if user_signed_in? %>
  <hr>
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/layouts/deleted_comment.html.haml
.comment
 - if comment.persisted?
  %p="User #{comment.user_id} says:"
  %strong= comment.content
  - unless current_user.is_author_of?(comment)
   = link_to 'Delete my comment', plymorphic_path(comment.parent, comment), method: :delete 